version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: xml-apis:xml-apis
    versions:
    - ">= 2.a, < 3"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:15"
  open-pull-requests-limit: 10
  target-branch: "maintenance/9.x"
  ignore:
  - dependency-name: xml-apis:xml-apis
    versions:
    - ">= 2.a, < 3"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
