/*
 * Copyright (C) 2018-2020 52°North Initiative for Geospatial Open Source
 * Software GmbH
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation.
 *
 * If the program is linked with libraries which are licensed under one of
 * the following licenses, the combination of the program with the linked
 * library is not considered a "derivative work" of the program:
 *
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 *
 * Therefore the distribution of the program linked with libraries licensed
 * under the aforementioned licenses, is permitted by the copyright holders
 * if the distribution is compliant with both the GNU General Public
 * License version 2 and the aforementioned licenses.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 */

package org.n52.shetland.ogc.sensorML.elements;

import org.n52.shetland.ogc.gml.time.Time;
import org.n52.shetland.ogc.sensorML.SmlContactList;
import org.n52.shetland.ogc.swe.AbstractSWEIdentifiable;

import java.util.List;

/**
 * @author <a href="mailto:j.speckamp@52north.org">Jan Speckamp</a>
 */
public class SmlEvent extends AbstractSWEIdentifiable {

    private String definition;

    // not implemented yet!
    //private SmlKeywordList keywords;

    private SmlIdentifierList identification;

    private SmlClassifierList classification;

    private SmlContactList contacts;

    private SmlDocumentationList documentation;

    /**
     * As of 12-000r2 the PDF Specification defines property as a single property but schemas.opengis.net defines it
     * as an unbounded array. As we are based on autogenerated code from schemas.opengis.net we do not strictly
     * follow the specification here
     */
    private List<SmlProperty> property;

    private Time time;

    // not implemented yet!
    // private SmlConfiguration configuration;

    public String getDefinition() {
        return definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public SmlIdentifierList getIdentification() {
        return identification;
    }

    public void setIdentification(SmlIdentifierList identification) {
        this.identification = identification;
    }

    public SmlClassifierList getClassification() {
        return classification;
    }

    public void setClassification(SmlClassifierList classification) {
        this.classification = classification;
    }

    public SmlContactList getContacts() {
        return contacts;
    }

    public void setContacts(SmlContactList contacts) {
        this.contacts = contacts;
    }

    public SmlDocumentationList getDocumentation() {
        return documentation;
    }

    public void setDocumentation(SmlDocumentationList documentation) {
        this.documentation = documentation;
    }

    public List<SmlProperty> getProperty() {
        return property;
    }

    public void setProperty(List<SmlProperty> property) {
        this.property = property;
    }

    public Time getTime() {
        return time;
    }

    public void setTime(Time time) {
        this.time = time;
    }

}
