/*
 * Copyright 2015-2020 52°North Initiative for Geospatial Open Source
 * Software GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.n52.shetland.ogc.sensorML.elements;

import org.n52.shetland.ogc.gml.time.Time;
import org.n52.shetland.ogc.sensorML.SmlContactList;
import org.n52.shetland.ogc.swe.AbstractSWEIdentifiable;

import java.util.List;

/**
 * @author <a href="mailto:j.speckamp@52north.org">Jan Speckamp</a>
 */
public class SmlEvent extends AbstractSWEIdentifiable {

    private String definition;

    // not implemented yet!
    //private SmlKeywordList keywords;

    private List<SmlIdentifier> identification;

    private SmlClassifierList classification;

    private SmlContactList contacts;

    private SmlDocumentationList documentation;

    /**
     * As of 12-000r2 the PDF Specification defines property as a single property but schemas.opengis.net defines it
     * as an unbounded array. As we are based on autogenerated code from schemas.opengis.net we do not strictly
     * follow the specification here
     */
    private List<SmlProperty> property;

    private Time time;

    // not implemented yet!
    // private SmlConfiguration configuration;

    public boolean isSetDefinition() {
        return definition != null && !definition.isEmpty();
    }

    public String getDefinition() {
        return definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public List<SmlIdentifier> getIdentification() {
        return identification;
    }

    public void setIdentification(List<SmlIdentifier> identification) {
        this.identification = identification;
    }

    public SmlClassifierList getClassification() {
        return classification;
    }

    public void setClassification(SmlClassifierList classification) {
        this.classification = classification;
    }

    public SmlContactList getContacts() {
        return contacts;
    }

    public void setContacts(SmlContactList contacts) {
        this.contacts = contacts;
    }

    public SmlDocumentationList getDocumentation() {
        return documentation;
    }

    public void setDocumentation(SmlDocumentationList documentation) {
        this.documentation = documentation;
    }

    public List<SmlProperty> getProperty() {
        return property;
    }

    public void setProperty(List<SmlProperty> property) {
        this.property = property;
    }

    public boolean isSetTime() {
        return time != null;
    }
    
    public Time getTime() {
        return time;
    }

    public void setTime(Time time) {
        this.time = time;
    }

}
