name: Java CI on Pull Request

on:
  pull_request:
  workflow_dispatch:


jobs:
  build-java-8:
    if: github.ref == 'refs/heads/maintenance/*'
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }} compile
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Build with Maven
      run: mvn -U -B clean install
  build-java-11:
    if: github.ref != 'refs/heads/version/v10.0'
    strategy:
      matrix:
        java: [ 11, 17 ]
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }} compile
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Build with Maven
      run: mvn -U -B clean install
